[package]
name = "crumbvote-database"
version = "0.1.0"
edition = "2024"

[dependencies]
sea-orm = { version = "2.0.0", default-features = false, features = ["sqlx-sqlite", "runtime-tokio", "macros", "sqlite-use-returning-for-3_35"] }
sea-orm-migration = { version = "2.0.0", default-features = false, features = ["sqlx-sqlite", "runtime-tokio"] }

[dev-dependencies]
tokio = { version = "1.53.1", features = ["macros", "rt-multi-thread"] }
